name: firebase
description: Firebase libraries for Dart on the web and server
version: 9.0.3-dev

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'

dependencies:
  http: ^0.12.2
  http_parser: ^3.1.4
  js: ^0.6.2
